version: "3"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    volumes:
      - acme:/etc/acme.sh
    volumes_from:
      - nginx-proxy:rw
    environment:
      - DEFAULT_EMAIL=ameenmohammed2311@gmail.com


networks:
  default:
    external:
      name: webproxy

volumes:
  certs:
  vhost:
  html:
  acme:
